# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.available_locale:
        class: AppBundle\Form\Type\AvailableLocaleType
        arguments:
            - '@translator.default'
        tags:
            - { name: form.type, alias: available_locale }
    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments:
            - '%kernel.default_locale%'
        tags:
            - { name: kernel.event_subscriber }
    app.users.listener:
        class: AppBundle\EventListener\UserListener
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
            - '@session'
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
            - { name: kernel.event_listener, event: kernel.controller, method: controllerActivated }
