<?php

namespace AppBundle\Repository;

/**
 * CacaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CacaRepository extends \Doctrine\ORM\EntityRepository
{
}
