<?php

namespace AppBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTicketWithAuthor($user, $page, $number)
    {
        $query = $this->createQueryBuilder('t')
                      ->andWhere('t.author = :id')
                      ->setFirstResult($page * $number)
                      ->setMaxResults($number)
                      ->setParameter('id', $user->getId())
                      ->addOrderBy('t.status', 'ASC')
                      ->getQuery();

        return $query->execute();
    }

    public function getNb() {
        return $this->createQueryBuilder('ticket')
                        ->select('COUNT(ticket)')
                        ->getQuery()
                        ->getSingleScalarResult();
    }
}
